name: Update Design System

on:
  repository_dispatch:
    types: [figma-webhook, LIBRARY_PUBLISH]

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug Payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Received payload:"
          echo "$PAYLOAD"

      - name: Process Figma update
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          WEBHOOK_PASSCODE: ${{ secrets.WEBHOOK_PASSCODE }}
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Processing Figma update"
          
          # Extract relevant information
          FILE_NAME=$(echo "$PAYLOAD" | grep -o '"file_name":"[^"]*' | cut -d'"' -f4)
          DESCRIPTION=$(echo "$PAYLOAD" | grep -o '"description":"[^"]*' | cut -d'"' -f4)
          TIMESTAMP=$(echo "$PAYLOAD" | grep -o '"timestamp":"[^"]*' | cut -d'"' -f4)
          
          echo "File Name: $FILE_NAME"
          echo "Description: $DESCRIPTION"
          echo "Timestamp: $TIMESTAMP"
          
          # Update data.json
          if [ ! -f data.json ]; then
            echo "[]" > data.json
          fi
          
          NEW_DATA=$(cat data.json | sed '1s/^/[{"file_name": "'$FILE_NAME'", "description": "'$DESCRIPTION'", "timestamp": "'$TIMESTAMP'"},/')
          echo "$NEW_DATA" > data.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update design system data" || exit 0
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .